# Generated by Django 3.2.13 on 2022-04-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=200)),
                ('minimum', models.FloatField()),
                ('average', models.FloatField()),
                ('maximum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=200)),
                ('minimum', models.FloatField()),
                ('average', models.FloatField()),
                ('maximum', models.FloatField()),
            ],
        ),
    ]
